<?php

return [
    'erro_login_invalido' => 'Correo o contraseña incorrectos.',
    'erro_email_existente' => 'Ya existe una cuenta con este correo.',
    'erro_campos_invalidos' => 'Por favor completa todos los campos correctamente.',
    'erro_senha_fraca' => 'La contraseña debe tener al menos 8 caracteres, con mayúscula, minúscula, número y carácter especial.',
    'erro_senha_confirmacao' => 'Las contraseñas no coinciden.',

    'login_saudacao' => '¡Hola de nuevo! 👋',
    'login_subtitulo' => 'Tu asistente te extrañaba.',
    'login_titulo' => 'Iniciar sesión',
    'campo_email' => 'Correo electrónico',
    'email_placeholder' => 'tu@correo.com',
    'nome_placeholder' => 'Mariana',
    'campo_senha' => 'Contraseña',
    'senha_placeholder' => 'Tu contraseña',
    'link_esqueceu_senha' => '¿Olvidaste tu contraseña?',
    'botao_entrar' => 'Iniciar sesión',
    'botao_google_login' => 'Iniciar sesión con Google',
    'botao_google_cadastro' => 'Registrarse con Google',
    'erro_google_login' => 'No se pudo autenticar con Google. Intenta de nuevo.',
    'divisor_ou' => 'o',
    'login_sem_conta' => '¿Aún no tienes cuenta?',
    'link_criar_conta' => 'Crea una gratis',
    'login_headline_desktop' => 'Tu agenda, directo en WhatsApp 📅',
    'login_subtitulo_desktop' => 'Dile a tu asistente lo que necesitas y listo. Sin apps extra, sin complicaciones.',
    'login_feature_1' => 'Agenda por mensaje, como con un amigo',
    'login_feature_2' => 'Recordatorios automáticos a tiempo',
    'login_feature_3' => 'Sincronizado con tu Google Calendar',
    'login_social_proof' => '+2.000 personas ya organizan su vida',

    'botao_iniciar_sesion' => 'Iniciar sesión',
    'botao_atras' => 'Atrás',
    'botao_continuar' => 'Continuar',

    'cadastro_step_label' => 'Paso 1 de 4 · Tu cuenta',
    'cadastro_titulo' => 'Crea tu cuenta',
    'cadastro_subtitulo' => 'En menos de 2 minutos tu agenda vive en WhatsApp.',
    'campo_nombre' => 'Tu nombre',
    'campo_senha_minima' => 'Mínimo 8 caracteres',
    'hint_senha' => 'Mínimo 8 caracteres, con mayúscula, minúscula, número y carácter especial.',
    'senha_mostrar' => 'Mostrar contraseña',
    'campo_confirmar_senha' => 'Confirmar contraseña',
    'senha_confirmar_placeholder' => 'Repite tu contraseña',
    'cadastro_microlegal' => 'Al continuar aceptas los <a class="link" href="#">Términos</a> y el <a class="link" href="#">Aviso de privacidad</a>.',
    'cadastro_headline_desktop' => 'Empieza en 2 minutos',
    'cadastro_subtitulo_desktop' => 'Crea tu cuenta y deja que tu asistente se encargue de tu agenda.',
    'cadastro_feature_1' => 'Configuración rápida y sencilla',
    'cadastro_feature_2' => 'Cancela cuando quieras',
    'cadastro_feature_3' => 'Hecho para México 🇲🇽',

    'pago_step_label' => 'Paso 2 de 4 · Pago',
    'pago_titulo' => 'Activa tu prueba',
    'pago_subtitulo_desktop' => 'No se te cobra nada hoy. Te avisamos 1 día antes del primer cobro.',
    'plan_pill' => '🎁 7 días gratis · Hoy no se cobra nada',
    'plan_price' => 'MX$64',
    'plan_price_small' => '/ mes después de la prueba',
    'plan_feature_1' => 'Eventos ilimitados desde WhatsApp',
    'plan_feature_2' => 'Recordatorios automáticos',
    'plan_feature_3' => 'Sync con Google Calendar',
    'plan_feature_4' => 'Cancela cuando quieras',
    'campo_numero_tarjeta' => 'Número de tarjeta',
    'campo_vencimiento' => 'Vencimiento',
    'campo_cvc' => 'CVC',
    'campo_nombre_tarjeta' => 'Nombre en la tarjeta',
    'botao_empezar_prueba' => 'Empezar mi prueba gratis',
    'pago_trust' => '🔒 Pago seguro con Stripe · Te avisamos 1 día antes de cualquier cobro',
    'pago_botao_checkout' => 'Continuar al pago',
    'pago_cancelado' => 'Pago cancelado. Intenta de nuevo.',
    'pago_erro_plano' => 'Plan no configurado para pagos. Contacta soporte.',
    'pago_erro_stripe' => 'Error al procesar el pago. Intenta de nuevo.',
    'pago_processando' => 'Procesando...',

    'google_step_label' => 'Paso 3 de 4 · Google Calendar',
    'google_titulo' => 'Conecta tu Google Calendar',
    'google_subtitulo' => 'Aquí es donde tu asistente guarda y lee tus eventos. Sin esto, no hay magia. ✨',
    'google_titulo_desktop' => 'Casi listo 📅',
    'google_subtitulo_desktop' => 'Conecta tu calendario para que tu asistente trabaje por ti.',
    'google_perm_1' => 'Ver tus eventos para responder "¿qué tengo hoy?"',
    'google_perm_2' => 'Crear y editar eventos que tú pidas por WhatsApp',
    'google_perm_3' => 'Nunca leemos tu correo ni tus archivos',
    'botao_conectar_google' => 'Conectar con Google',
    'google_microlegal' => 'Te llevaremos a Google y regresarás aquí en segundos.',

    'whatsapp_step_label' => 'Paso 4 de 4 · WhatsApp',
    'whatsapp_titulo' => '¿A qué número te escribimos?',
    'whatsapp_subtitulo' => 'Tu asistente solo responde a este número. Es tu línea directa.',
    'whatsapp_titulo_desktop' => 'El último paso: tu WhatsApp',
    'whatsapp_subtitulo_desktop' => 'Tu asistente solo responde a tu número. Es tu línea directa, privada y segura.',
    'campo_whatsapp' => 'Tu número de WhatsApp',
    'whatsapp_aviso' => 'Te mandaremos un mensaje de bienvenida para confirmar. 🎉',
    'botao_conectar_whatsapp' => 'Conectar mi WhatsApp',
    'whatsapp_feature_1' => 'Mensaje de bienvenida al instante',
    'whatsapp_feature_2' => 'Funciona en WhatsApp normal y Business',
    'whatsapp_sep' => 'o si prefieres',
    'whatsapp_qr_titulo' => 'Escanéa y empieza a chatear',
    'whatsapp_qr_texto' => 'Abre la cámara, escanea el código y tu asistente te saluda al instante.',

    'home_saludo' => '¡Hola, Mariana! 👋',
    'home_subtitulo' => 'Todo listo. Tu agenda se maneja sola.',
    'badge_prueba_dias' => '🎁 Prueba · 5 días restantes',
    'badge_ativo' => '✅ Activo',
    'badge_expirado' => '⚠️ Expirado',
    'assist_titulo' => 'Escríbele a tu asistente',
    'assist_ejemplo' => '"Agéndame el dentista el jueves a las 4"',
    'botao_abrir' => 'Abrir',
    'botao_abrir_whatsapp' => 'Abrir WhatsApp',
    'home_conexiones_titulo' => 'Tus conexiones',
    'home_eventos_titulo' => 'Próximos eventos',
    'home_google_label' => 'Google Calendar',
    'home_whatsapp_label' => 'WhatsApp',
    'home_conectado' => 'Conectado',
    'home_activo' => 'Activo',
    'home_pendiente' => 'Pendiente',
    'home_sin_eventos' => 'Aún no tienes eventos próximos. Pídele a tu asistente que agende uno por WhatsApp.',
    'home_micro_note' => '😉 Para crear o cambiar eventos, solo escríbele a tu asistente por WhatsApp.',
    'home_semana_titulo' => 'Esta semana',
    'home_semana_eventos' => 'eventos',
    'home_semana_recordatorios' => 'recordatorios',

    'menu_inicio' => 'Inicio',
    'menu_cuenta' => 'Mi cuenta',
    'menu_whatsapp' => 'Abrir WhatsApp',
    'menu_salir' => 'Cerrar sesión',
    'badge_prueba' => '🎁 Prueba',
    'upgrade_botao' => 'Activar plan',
    'upgrade_ciclo_mensal' => '/ mes',
    'upgrade_ciclo_trimestral' => '/ trimestre',
    'upgrade_ciclo_anual' => '/ año',

    'conta_titulo' => 'Mi cuenta',
    'conta_suscripcion_titulo' => 'Suscripción',
    'plan_mensual' => 'Plan mensual',
    'plan_mensual_precio' => 'MX$64 /mes',
    'sub_dates' => 'Prueba gratis hasta el <b>17 jun</b>.<br>Primer cobro: <b>18 jun 2026</b>.',
    'botao_cambiar_tarjeta' => 'Cambiar tarjeta',
    'botao_cancelar_plan' => 'Cancelar plan',
    'preferencias_titulo' => 'Preferencias del asistente',
    'modo_silencio_titulo' => 'Modo silencio',
    'modo_silencio_sub' => 'No te escribimos de 10 pm a 7 am',
    'recordatorios_titulo' => 'Recordatorios',
    'recordatorios_sub' => 'Con cuánta antelación te avisamos',
    'recordatorio_15' => '15 min',
    'recordatorio_30' => '30 min',
    'recordatorio_1h' => '1 hora',
    'recordatorio_1d' => '1 día',
    'conexiones_titulo' => 'Conexiones',
    'botao_cambiar' => 'Cambiar',
    'botao_desconectar' => 'Desconectar',
    'sesion_titulo' => 'Sesión',
    'botao_cerrar_sesion' => 'Cerrar sesión',

    // Admin — Sidebar
    'admin_menu' => 'Menú',
    'admin_dashboard' => 'Dashboard',
    'admin_usuarios' => 'Usuarios',
    'admin_configuracao' => 'Configuración',
    'admin_sair' => 'Salir',

    // Admin — Login
    'admin_painel' => 'Panel administrativo',
    'admin_entrar' => 'Iniciar sesión',
    'admin_acesse_painel' => 'Accede al panel de administración.',
    'admin_email' => 'Correo electrónico',
    'admin_senha' => 'Contraseña',
    'admin_sua_senha' => 'Tu contraseña',
    'admin_login_erro' => 'Correo o contraseña incorrectos.',

    // Admin — Dashboard
    'admin_visao_geral' => 'Vista general del sistema',
    'admin_total_usuarios' => 'Total de usuarios',
    'admin_usuarios_ativos' => 'Usuarios activos',
    'admin_eventos_criados' => 'Eventos creados',
    'admin_mensagens_trocadas' => 'Mensajes intercambiados',
    'admin_em_trial' => 'En prueba',
    'admin_plano_ativo' => 'Plan activo',
    'admin_cancelados' => 'Cancelados',
    'admin_eventos_hoje' => 'Eventos hoy',
    'dash_receita_estimada' => 'Ingreso estimado',
    'dash_assinantes' => 'suscriptores activos',
    'dash_conversao' => 'Tasa de conversión',
    'dash_trial_para_ativo' => 'prueba → activo',
    'dash_novos_semana' => 'Nuevos esta semana',
    'dash_este_mes' => 'este mes',
    'dash_ativos' => 'activos',
    'dash_hoje' => 'hoy',
    'dash_grafico_atividade' => 'Actividad (últimos 30 días)',
    'dash_grafico_planos' => 'Distribución de planes',
    'dash_leg_usuarios' => 'Nuevos usuarios',
    'dash_leg_eventos' => 'Eventos',
    'dash_leg_mensagens' => 'Mensajes',
    'dash_inativos' => 'Inactivos',
    'dash_cancelamentos' => 'Cancelaciones',
    'dash_grafico_receita' => 'Ingreso por mes',
    'dash_grafico_usuarios' => 'Nuevos usuarios vs Cancelaciones (30 días)',
    'dash_resumo' => 'Resumen operativo',
    'admin_eventos_recentes' => 'Eventos recientes',
    'admin_titulo' => 'Título',
    'admin_usuario' => 'Usuario',
    'admin_data' => 'Fecha',
    'admin_lembrete' => 'Recordatorio',
    'admin_enviado' => 'Enviado',
    'admin_pendente' => 'Pendiente',
    'admin_nenhum_evento' => 'Ningún evento registrado aún.',

    // Admin — Usuarios
    'admin_usuario_encontrado' => 'usuario encontrado',
    'admin_usuarios_encontrados' => 'usuarios encontrados',
    'admin_novo_usuario' => 'Nuevo usuario',
    'admin_lista_usuarios' => 'Lista de usuarios',
    'admin_nome' => 'Nombre',
    'admin_email_col' => 'Correo',
    'admin_telefone' => 'Teléfono',
    'admin_plano' => 'Plan',
    'admin_status' => 'Estado',
    'admin_cadastro' => 'Registro',
    'admin_acoes' => 'Acciones',
    'admin_ativo' => 'Activo',
    'admin_inativo' => 'Inactivo',
    'admin_ativar' => 'Activar',
    'admin_desativar' => 'Desactivar',
    'admin_apagar' => 'Eliminar',
    'admin_confirmar_apagar' => '¿Estás seguro de que deseas eliminar este usuario?',
    'admin_editar' => 'Editar',
    'admin_buscar' => 'Buscar por nombre, correo...',
    'admin_todos_planos' => 'Todos los planes',
    'admin_nenhum_usuario' => 'Ningún usuario encontrado.',
    'admin_nome_completo' => 'Nombre completo',
    'admin_min_senha' => 'Mínimo 6 caracteres',
    'admin_expiracao_plano' => 'Expiración del plan',
    'admin_cancelar' => 'Cancelar',
    'admin_criar_usuario' => 'Crear usuario',
    'admin_editar_usuario' => 'Editar usuario',
    'admin_salvar' => 'Guardar cambios',
    'admin_usuario_criado' => 'Usuario creado exitosamente.',
    'admin_usuario_atualizado' => 'Usuario actualizado exitosamente.',
    'admin_usuario_ativado' => 'Usuario activado.',
    'admin_usuario_desativado' => 'Usuario desactivado.',
    'admin_usuario_apagado' => 'Usuario eliminado exitosamente.',
    'admin_erro_campos' => 'Nombre, correo y contraseña son obligatorios.',
    'admin_erro_senha_curta' => 'La contraseña debe tener al menos 6 caracteres.',
    'admin_erro_email_existe' => 'Ya existe un usuario con este correo.',
    'admin_erro_email_outro' => 'Ya existe otro usuario con este correo.',
    'admin_erro_nome_email' => 'Nombre y correo son obligatorios.',
    'admin_erro_telefone_existe' => 'Ya existe un usuario con este número de teléfono.',
    'admin_erro_telefone_outro' => 'Ya existe otro usuario con este número de teléfono.',
    'erro_telefone_existe' => 'Este número de WhatsApp ya está registrado en otra cuenta.',

    // Admin — Configuración
    'admin_config_subtitulo' => 'Variables de entorno y estado del sistema',
    'admin_preferencias' => 'Preferencias',
    'admin_idioma' => 'Idioma',
    'admin_idioma_desc' => 'Idioma predeterminado de la interfaz',
    'admin_fuso_horario' => 'Zona horaria',
    'admin_fuso_desc' => 'Zona horaria predeterminada para nuevos usuarios',
    'admin_salvar_prefs' => 'Guardar preferencias',
    'admin_prefs_salvas' => 'Preferencias guardadas exitosamente.',
    'admin_confirmar_titulo' => 'Confirmar cambio',
    'admin_confirmar_texto' => 'Estas son configuraciones críticas del sistema. Para confirmar, escribe la palabra de abajo.',
    'admin_confirmar_label' => 'Escribe CONFIRMAR para continuar',
    'admin_confirmar_placeholder' => 'CONFIRMAR',
    'admin_confirmar_palavra' => 'CONFIRMAR',
    'admin_confirmar_salvar' => 'Guardar cambios',
    'admin_geral' => 'General',
    'admin_moeda' => 'Moneda',
    'admin_moeda_desc' => 'Moneda usada en los precios y cobros',
    'admin_nome_app' => 'Nombre de la aplicación',
    'admin_nome_app_desc' => 'Se muestra en todo el sistema (títulos, sidebar, landing, etc)',
    'admin_contato_redes' => 'Contacto y redes sociales',
    'admin_link_suporte' => 'Link de soporte',
    'admin_link_suporte_desc' => 'Link mostrado como "Soporte" en el footer',
    'admin_email_suporte' => 'Correo de contacto',
    'admin_email_suporte_desc' => 'Mostrado en el footer de la landing page',
    'admin_instagram_desc' => 'Usuario de Instagram (con o sin @)',
    'admin_tiktok_desc' => 'Usuario de TikTok (con o sin @)',
    'admin_variaveis' => 'Variables de entorno',
    'admin_sistema' => 'Sistema',
    'admin_php_versao' => 'Versión del intérprete',
    'admin_servidor' => 'Servidor',
    'admin_servidor_desc' => 'Software del servidor web',
    'admin_modo_dev' => 'Modo dev',
    'admin_modo_dev_desc' => 'Simulaciones y bypass activados',
    'admin_ativado' => 'Activado',
    'admin_desativado' => 'Desactivado',

    // Admin — Planes
    'admin_planos' => 'Planes',
    'admin_planos_subtitulo' => 'Administra los planes disponibles',
    'admin_novo_plano' => 'Nuevo plan',
    'admin_lista_planos' => 'Lista de planes',
    'admin_plano_encontrado' => 'plan encontrado',
    'admin_planos_encontrados' => 'planes encontrados',
    'admin_nome_plano' => 'Nombre del plan',
    'admin_descricao' => 'Descripción',
    'admin_descricao_placeholder' => 'Breve descripción del plan',
    'admin_ciclo' => 'Ciclo',
    'admin_mensal' => 'Mensual',
    'admin_trimestral' => 'Trimestral',
    'admin_anual' => 'Anual',
    'admin_preco' => 'Precio',
    'admin_dias_teste' => 'Días de prueba',
    'admin_dias_teste_hint' => '0 = sin período de prueba',
    'admin_etiqueta_texto' => 'Etiqueta',
    'admin_etiqueta_placeholder' => 'Ej: Popular, Precio de lanzamiento',
    'admin_etiqueta_hint' => 'Texto del sello en la tarjeta. Vacío = predeterminado automático.',
    'admin_stripe_price_hint' => 'ID del precio en Stripe (ej: price_1Abc...). Copia del Dashboard de Stripe.',
    'admin_etiqueta_cor' => 'Color de la etiqueta',
    'admin_cor_amarelo' => 'Amarillo',
    'admin_cor_azul' => 'Azul',
    'admin_cor_verde' => 'Verde',
    'admin_cor_vermelho' => 'Rojo',
    'admin_cor_roxo' => 'Morado',
    'admin_todos_ciclos' => 'Todos los ciclos',
    'admin_nenhum_plano' => 'Ningún plan registrado.',
    'admin_criar_plano' => 'Crear plan',
    'admin_editar_plano' => 'Editar plan',
    'admin_plano_criado' => 'Plan creado exitosamente.',
    'admin_plano_atualizado' => 'Plan actualizado exitosamente.',
    'admin_plano_ativado' => 'Plan activado.',
    'admin_plano_desativado' => 'Plan desactivado.',
    'admin_plano_excluido' => 'Plan eliminado.',
    'admin_erro_nome_preco' => 'Nombre y precio son obligatorios.',
    'admin_excluir' => 'Eliminar',
    'admin_teste' => 'prueba',
    'admin_dias' => 'días',
    'admin_sem_teste' => 'Sin prueba',

    // Landing page
    'lp_title' => '%APP% — Tu agenda en WhatsApp',
    'lp_login' => 'Iniciar sesión',
    'lp_hero_h1' => 'Tu agenda, directo<br>en WhatsApp',
    'lp_hero_lead' => 'Dile a tu asistente lo que necesitas y listo. Sin apps extra, sin complicaciones.',
    'lp_hero_cta' => 'Probar gratis %d días',
    'lp_hero_cta_sem_teste' => 'Empezar ahora',
    'lp_hero_micro' => 'Sin tarjeta · Cancela cuando quieras',
    'lp_hero_micro_sem_teste' => 'Cancela cuando quieras',
    'lp_hero_social' => '+2.000 personas ya organizan su vida',
    'lp_how_eyebrow' => 'Así de simple',
    'lp_how_title' => '¿Cómo funciona?',
    'lp_how_sub' => 'Tres pasos y tu vida se organiza sola.',
    'lp_step1_title' => 'Conéctate en segundos',
    'lp_step1_text' => 'Registra tu número y empieza a chatear. No descargas nada.',
    'lp_step2_title' => 'Escríbele como a un amigo',
    'lp_step2_text' => '"Agéndame el dentista el jueves a las 4." Él entiende y lo guarda.',
    'lp_step3_title' => 'Te avisamos a tiempo',
    'lp_step3_text' => 'Recordatorios automáticos para que no se te pase nada.',
    'lp_demo_eyebrow' => 'Velo en acción',
    'lp_demo_title' => 'Habla. Se organiza solo.',
    'lp_demo_sub' => 'Una conversación normal. Eso es todo.',
    'lp_demo_online' => '● en línea',
    'lp_demo_note' => 'Funciona en el mismo WhatsApp que ya usas 💬',
    'lp_demo_me1' => 'Agéndame una reunión con el doctor mañana 11am',
    'lp_demo_them1' => '✅ Listo, agendé tu cita. Te aviso 30 min antes.',
    'lp_demo_stamp1' => 'mar 13 jun · 11:00am',
    'lp_demo_me2' => '¿Qué tengo esta semana?',
    'lp_demo_them2' => '📅 Tienes 3 eventos: doctor, comida con mamá y pago de renta.',
    'lp_demo_stamp2' => 'esta semana',
    'lp_ben_eyebrow' => 'Por qué te va a encantar',
    'lp_ben_title' => 'Hecho para tu día a día',
    'lp_ben1_title' => 'Sin descargar nada',
    'lp_ben1_text' => 'Vive en tu WhatsApp.',
    'lp_ben2_title' => 'Sync con Google',
    'lp_ben2_text' => 'Se conecta a tu calendario.',
    'lp_ben3_title' => 'Recordatorios auto',
    'lp_ben3_text' => 'Te avisa antes de cada cita.',
    'lp_ben4_title' => 'Modo silencio',
    'lp_ben4_text' => 'Respeta tus horas de descanso.',
    'lp_ben5_title' => 'Datos seguros',
    'lp_ben5_text' => 'Tu información, protegida.',
    'lp_ben6_title' => 'Hecho para México',
    'lp_ben6_flag' => '🇲🇽',
    'lp_ben6_text' => 'Habla tu idioma y tu hora.',
    'lp_price_eyebrow_single' => 'Un solo plan, sin enredos',
    'lp_price_eyebrow_multi' => 'Elige tu plan',
    'lp_price_title' => 'Precio',
    'lp_price_default_name' => 'Plan %APP%',
    'lp_price_default_was' => 'antes <s>MX$99</s> · ahorra 35%',
    'lp_price_tag_launch' => '🏆 Precio de lanzamiento',
    'lp_price_tag_trial' => '🎁 %d días gratis',
    'lp_price_cta' => 'Comenzar prueba gratis',
    'lp_price_cta_sem_teste' => 'Suscribirse ahora',
    'lp_price_guarantee' => '🛡️ %d días gratis · sin compromiso',
    'lp_feat1' => 'Agendamiento por WhatsApp ilimitado',
    'lp_feat2' => 'Sincronización con Google Calendar',
    'lp_feat3' => 'Recordatorios automáticos',
    'lp_feat4' => 'Modo silencio personalizable',
    'lp_feat5' => 'Soporte por WhatsApp',
    'lp_faq_eyebrow' => '¿Dudas?',
    'lp_faq_title' => 'Preguntas frecuentes',
    'lp_faq1_q' => '¿Necesito instalar algo?',
    'lp_faq1_a' => 'No. %APP% funciona dentro de WhatsApp, la app que ya tienes. Solo registras tu número y listo.',
    'lp_faq2_q' => '¿Funciona con mi Google Calendar?',
    'lp_faq2_a' => 'Sí. Se sincroniza con tu Google Calendar para que todo esté en un mismo lugar, al instante.',
    'lp_faq3_q' => '¿Qué pasa si cancelo?',
    'lp_faq3_a' => 'Cancelas cuando quieras, sin penalización. Tus eventos siguen en tu calendario normal.',
    'lp_faq4_q' => '¿Mis datos están seguros?',
    'lp_faq4_a' => 'Tu información se cifra y nunca se comparte. Solo tú y tu asistente tienen acceso.',
    'lp_faq5_q' => '¿Funciona en cualquier WhatsApp?',
    'lp_faq5_a' => 'Sí, funciona en WhatsApp normal y Business, en Android y iPhone.',
    'lp_final_title' => 'Empieza a organizarte hoy 🚀',
    'lp_final_text' => 'Únete a miles de personas que ya dejaron el caos atrás con %APP%.',
    'lp_final_cta' => 'Crear mi cuenta gratis',
    'lp_final_cta_sem_teste' => 'Crear mi cuenta',
    'lp_final_micro' => '%d días gratis · Sin tarjeta · Cancela cuando quieras',
    'lp_final_micro_sem_teste' => 'Cancela cuando quieras',
    'lp_footer_copy' => '© %d %APP% · Hecho con 💙 en México',
    'lp_privacy' => 'Privacidad',
    'lp_terms' => 'Términos',
    'lp_support' => 'Soporte',
    'lp_contact' => 'Contacto',
    'lp_ciclo_mensal' => '/mes',
    'lp_ciclo_trimestral' => '/trim',
    'lp_ciclo_anual' => '/año',
    'lp_moeda' => 'MX$',

    // Modais conta
    'modal_cambiar_plan' => 'Cambiar de plan',
    'modal_cambiar_plan_sub' => 'Tu plan actual está marcado. El cambio aplica en tu próximo ciclo.',
    'modal_plan_actual' => '✓ Plan actual',
    'modal_cambiar_a_este' => 'Cambiar a este',
    'modal_facturacion' => 'Facturación',
    'modal_facturado_anual' => '%s facturado al año',
    'modal_trust_plan' => '🔒 Pago seguro con Stripe · Cambia o cancela en cualquier momento',
    'modal_cambiar_tarjeta' => 'Cambiar tarjeta',
    'modal_cambiar_tarjeta_sub' => 'Actualiza el método de pago de tu suscripción.',
    'modal_num_tarjeta' => 'Número de tarjeta',
    'modal_vencimiento' => 'Vencimiento',
    'modal_nombre_tarjeta' => 'Nombre en la tarjeta',
    'modal_guardar_tarjeta' => 'Guardar tarjeta',
    'modal_trust_tarjeta' => '🔒 Tus datos se procesan de forma segura con Stripe',
    'modal_cancelar_plan' => '¿Cancelar tu plan?',
    'modal_cancelar_sub' => 'Tu asistente dejará de organizar tu agenda al terminar el ciclo actual.',
    'modal_cancelar_alerta' => 'Si te quedas, conservas el agendamiento ilimitado, los recordatorios y la sincronización con Google hasta el',
    'modal_mantener' => 'Mantener mi plan',
    'modal_si_cancelar' => 'Sí, cancelar plan',
    'modal_ahorra' => 'Ahorra %d%%',
    'modal_todo_del_plan' => 'Todo lo del plan mensual',
    'modal_meses_gratis' => '2 meses gratis',
    'modal_precio_fijo' => 'Precio fijo todo el año',

    // Política de Privacidadr
    'lang_code' => 'es-MX',
    'priv_titulo' => 'Aviso de Privacidad',
    'priv_atualizado' => 'Última actualización: 22 de junio de 2026',

    'priv_s1_titulo' => 'Introducción',
    'priv_s1_texto' => '%APP% ("nosotros", "nuestro") es un servicio de agendamiento personal que integra WhatsApp y Google Calendar. Este aviso describe cómo recopilamos, usamos, almacenamos y protegemos sus datos personales, conforme a la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP, México) y la Lei Geral de Proteção de Dados (LGPD — Ley 13.709/2018, Brasil).',

    'priv_s2_titulo' => 'Datos que recopilamos',
    'priv_s2_texto' => 'Recopilamos únicamente los datos necesarios para prestar el servicio:',
    'priv_s2_item1' => '<strong>Datos de registro:</strong> nombre, correo electrónico, contraseña (almacenada con hash criptográfico) y número telefónico.',
    'priv_s2_item2' => '<strong>Datos de agenda:</strong> eventos creados, editados o cancelados por usted vía WhatsApp, sincronizados con Google Calendar.',
    'priv_s2_item3' => '<strong>Tokens de autenticación:</strong> tokens OAuth de Google, utilizados exclusivamente para acceder a su calendario con su autorización.',
    'priv_s2_item4' => '<strong>Mensajes en WhatsApp:</strong> registramos el contenido de los mensajes intercambiados con el asistente para procesamiento y registro de atención.',
    'priv_s2_item5' => '<strong>Datos de pago:</strong> procesados directamente por Stripe. No almacenamos número de tarjeta, CVV ni datos bancarios en nuestros servidores.',

    'priv_s3_titulo' => 'Finalidades del tratamiento',
    'priv_s3_texto' => 'Utilizamos sus datos para:',
    'priv_s3_item1' => 'Crear y administrar su cuenta y suscripción.',
    'priv_s3_item2' => 'Procesar comandos de agendamiento recibidos vía WhatsApp y sincronizar con Google Calendar.',
    'priv_s3_item3' => 'Enviar recordatorios y notificaciones sobre sus eventos.',
    'priv_s3_item4' => 'Mejorar el servicio y corregir problemas técnicos.',

    'priv_s4_titulo' => 'Fundamento legal',
    'priv_s4_texto' => 'En México, el tratamiento se fundamenta en su consentimiento otorgado al crear su cuenta y autorizar el acceso a Google Calendar, conforme a la LFPDPPP (arts. 8 y 17). En Brasil, las bases legales son el consentimiento (art. 7º, I de la LGPD), la ejecución de contrato (art. 7º, V) y el interés legítimo (art. 7º, IX) para el envío de recordatorios, los cuales puede desactivar en cualquier momento en la configuración de su cuenta.',

    'priv_s5_titulo' => 'Sus derechos',
    'priv_s5_texto' => 'Conforme a la LFPDPPP (México) y la LGPD (Brasil), usted tiene derecho a:',
    'priv_s5_item1' => '<strong>Acceso:</strong> solicitar una copia de los datos personales que mantenemos sobre usted.',
    'priv_s5_item2' => '<strong>Rectificación:</strong> corregir datos incompletos o inexactos.',
    'priv_s5_item3' => '<strong>Cancelación / Eliminación:</strong> solicitar la supresión de sus datos personales.',
    'priv_s5_item4' => '<strong>Oposición:</strong> oponerse al tratamiento de sus datos para determinada finalidad.',
    'priv_s5_item5' => '<strong>Portabilidad:</strong> recibir sus datos en formato estructurado e interoperable (LGPD).',
    'priv_s5_item6' => '<strong>Revocación del consentimiento:</strong> retirar el consentimiento en cualquier momento, sin afectar la licitud del tratamiento previo.',

    'priv_s6_titulo' => 'Transferencia de datos',
    'priv_s6_texto' => 'Compartimos datos únicamente con los servicios necesarios para la operación: Google (sincronización de calendario vía OAuth), Stripe (procesamiento de pagos), Evolution API / WhatsApp (envío y recepción de mensajes) y n8n (orquestación de automatizaciones). No vendemos, alquilamos ni cedemos sus datos a terceros con fines de mercadotecnia.',

    'priv_s7_titulo' => 'Almacenamiento y seguridad',
    'priv_s7_texto' => 'Sus datos se almacenan en servidores con acceso restringido. Las contraseñas se protegen con hash criptográfico (bcrypt). Los tokens de Google se almacenan de forma cifrada. Adoptamos medidas técnicas y organizacionales para proteger sus datos contra acceso no autorizado, destrucción, pérdida o alteración.',

    'priv_s8_titulo' => 'Retención de datos',
    'priv_s8_texto' => 'Mantenemos sus datos mientras su cuenta esté activa. Al solicitar la eliminación de la cuenta, sus datos personales serán removidos en un plazo de 30 días, excepto cuando exista obligación legal de conservación (como registros fiscales de pago).',

    'priv_s9_titulo' => 'Transferencia internacional',
    'priv_s9_texto' => 'Sus datos pueden ser procesados en servidores ubicados fuera de México o Brasil (ej: Google Cloud, Stripe). En estos casos, garantizamos que los destinatarios ofrezcan un nivel adecuado de protección, conforme a lo exigido por la LFPDPPP (art. 36) y la LGPD (art. 33).',

    'priv_s10_titulo' => 'Contacto y oficial de datos',
    'priv_s10_texto' => 'Para ejercer sus derechos ARCO (Acceso, Rectificación, Cancelación y Oposición) o aclarar dudas sobre este aviso, contáctenos por correo electrónico: contacto@calendarioia.com. Las solicitudes ARCO serán respondidas en el plazo de 20 días establecido por la LFPDPPP. Para usuarios en Brasil, el encargado de protección de datos puede ser contactado en la misma dirección.',

    // Términos de Uso
    'termos_titulo' => 'Términos y Condiciones de Uso',
    'termos_atualizado' => 'Última actualización: 22 de junio de 2026',

    'termos_s1_titulo' => 'Aceptación de los términos',
    'termos_s1_texto' => 'Al crear una cuenta o utilizar %APP%, usted acepta estos Términos y Condiciones de Uso y nuestro Aviso de Privacidad. Si no está de acuerdo, no utilice el servicio.',

    'termos_s2_titulo' => 'Descripción del servicio',
    'termos_s2_texto' => '%APP% es un servicio de agendamiento personal que le permite crear, listar, editar y cancelar eventos a través de mensajes en lenguaje natural por WhatsApp, con sincronización automática a Google Calendar. El servicio incluye:',
    'termos_s2_item1' => 'Asistente de agendamiento vía WhatsApp con inteligencia artificial.',
    'termos_s2_item2' => 'Sincronización bidireccional con Google Calendar.',
    'termos_s2_item3' => 'Recordatorios automáticos de eventos.',

    'termos_s3_titulo' => 'Registro y cuenta',
    'termos_s3_texto' => 'Para utilizar el servicio, usted debe:',
    'termos_s3_item1' => 'Tener al menos 18 años de edad o la mayoría de edad legal en su jurisdicción.',
    'termos_s3_item2' => 'Proporcionar información veraz y actualizada en el registro.',
    'termos_s3_item3' => 'Mantener la confidencialidad de su contraseña. Usted es responsable de toda actividad realizada con su cuenta.',
    'termos_s3_item4' => 'Notificarnos de inmediato en caso de uso no autorizado de su cuenta.',

    'termos_s4_titulo' => 'Planes y pago',
    'termos_s4_texto' => '%APP% ofrece planes de pago con ciclos mensual, trimestral o anual, y puede ofrecer un período de prueba gratuito. Los precios se muestran en pesos mexicanos (MXN) y se cobran a través de Stripe. La renovación es automática al final de cada ciclo. Puede cancelar en cualquier momento desde el panel del cliente; el acceso permanece activo hasta el fin del ciclo ya pagado. No se realizan reembolsos por períodos parciales, excepto cuando lo exija la ley aplicable, incluyendo la Ley Federal de Protección al Consumidor.',

    'termos_s5_titulo' => 'Uso aceptable',
    'termos_s5_texto' => 'Usted se compromete a no utilizar el servicio para:',
    'termos_s5_item1' => 'Enviar mensajes automatizados masivos (spam) vía WhatsApp.',
    'termos_s5_item2' => 'Intentar acceder a cuentas de otros usuarios o sistemas internos.',
    'termos_s5_item3' => 'Utilizar el servicio para cualquier finalidad ilegal o que viole derechos de terceros.',
    'termos_s5_item4' => 'Revender, sublicenciar o redistribuir el acceso al servicio sin autorización.',

    'termos_s6_titulo' => 'Propiedad intelectual',
    'termos_s6_texto' => 'Todo el contenido, marca, código y diseño de %APP% son de nuestra propiedad o están licenciados a nosotros. Usted mantiene la propiedad de los datos y eventos que ingrese en el servicio. Al utilizar el servicio, nos otorga una licencia limitada para procesar sus datos exclusivamente para la prestación del servicio contratado.',

    'termos_s7_titulo' => 'Integraciones con terceros',
    'termos_s7_texto' => 'El servicio depende de plataformas de terceros (Google, WhatsApp/Meta, Stripe). No nos responsabilizamos por indisponibilidades, cambios de política o interrupciones en dichos servicios. En caso de descontinuación de una integración esencial, notificaremos a los usuarios con anticipación razonable.',

    'termos_s8_titulo' => 'Limitación de responsabilidad',
    'termos_s8_texto' => '%APP% se proporciona "tal cual". Nos esforzamos por mantener el servicio estable y seguro, pero no garantizamos disponibilidad ininterrumpida. No nos responsabilizamos por compromisos perdidos por falla de notificación, sincronización o por indisponibilidad de los servicios de terceros. Nuestra responsabilidad total se limita al monto pagado por usted en los últimos 12 meses.',

    'termos_s9_titulo' => 'Suspensión y cancelación',
    'termos_s9_texto' => 'Nos reservamos el derecho de suspender o cancelar su cuenta en caso de violación de estos términos, uso abusivo o falta de pago. Usted puede cancelar su cuenta en cualquier momento desde el panel o contactándonos. Al cancelar, sus datos serán tratados conforme al Aviso de Privacidad.',

    'termos_s10_titulo' => 'Modificaciones a los términos',
    'termos_s10_texto' => 'Podemos actualizar estos términos periódicamente. Los cambios relevantes serán comunicados por correo electrónico o notificación en el servicio con al menos 15 días de anticipación. El uso continuado del servicio después de los cambios constituye aceptación de los nuevos términos.',

    'termos_s11_titulo' => 'Ley aplicable y jurisdicción',
    'termos_s11_texto' => 'Para usuarios en México, estos términos se rigen por las leyes federales de los Estados Unidos Mexicanos, incluyendo la LFPDPPP y la Ley Federal de Protección al Consumidor, con jurisdicción en los tribunales competentes de la Ciudad de México. Para usuarios en Brasil, se aplican la LGPD, el Marco Civil de Internet (Ley 12.965/2014) y el Código de Defensa del Consumidor (Ley 8.078/1990), con fuero en el domicilio del consumidor.',

    'termos_s12_titulo' => 'Contacto',
    'termos_s12_texto' => 'Para dudas sobre estos términos, contáctenos por correo electrónico: contacto@calendarioia.com.',
];
