<?php

return [
    'erro_login_invalido' => 'Correo o contraseña incorrectos.',
    'erro_email_existente' => 'Ya existe una cuenta con este correo.',
    'erro_campos_invalidos' => 'Por favor completa todos los campos correctamente.',

    'login_saudacao' => '¡Hola de nuevo! 👋',
    'login_subtitulo' => 'Tu asistente te extrañaba.',
    'login_titulo' => 'Iniciar sesión',
    'campo_email' => 'Correo electrónico',
    'campo_senha' => 'Contraseña',
    'senha_placeholder' => 'Tu contraseña',
    'link_esqueceu_senha' => '¿Olvidaste tu contraseña?',
    'botao_entrar' => 'Iniciar sesión',
    'login_sem_conta' => '¿Aún no tienes cuenta?',
    'link_criar_conta' => 'Crea una gratis',
    'login_headline_desktop' => 'Tu agenda, directo en WhatsApp 📅',
    'login_subtitulo_desktop' => 'Dile a tu asistente lo que necesitas y listo. Sin apps extra, sin complicaciones.',
    'login_feature_1' => 'Agenda por mensaje, como con un amigo',
    'login_feature_2' => 'Recordatorios automáticos a tiempo',
    'login_feature_3' => 'Sincronizado con tu Google Calendar',
    'login_social_proof' => '+2.000 personas ya organizan su vida',

    'botao_iniciar_sesion' => 'Iniciar sesión',
    'botao_atras' => 'Atrás',
    'botao_continuar' => 'Continuar',

    'cadastro_step_label' => 'Paso 1 de 4 · Tu cuenta',
    'cadastro_titulo' => 'Crea tu cuenta',
    'cadastro_subtitulo' => 'En menos de 2 minutos tu agenda vive en WhatsApp.',
    'campo_nombre' => 'Tu nombre',
    'campo_senha_minima' => 'Mínimo 8 caracteres',
    'hint_senha' => 'Usa al menos 8 caracteres.',
    'cadastro_microlegal' => 'Al continuar aceptas los <a class="link" href="#">Términos</a> y el <a class="link" href="#">Aviso de privacidad</a>.',
    'cadastro_headline_desktop' => 'Empieza gratis en 2 minutos',
    'cadastro_subtitulo_desktop' => 'Crea tu cuenta y deja que tu asistente se encargue de tu agenda.',
    'cadastro_feature_1' => '7 días gratis, sin tarjeta para probar',
    'cadastro_feature_2' => 'Cancela cuando quieras',
    'cadastro_feature_3' => 'Hecho para México 🇲🇽',

    'pago_step_label' => 'Paso 2 de 4 · Pago',
    'pago_titulo' => 'Activa tu prueba',
    'pago_subtitulo_desktop' => 'No se te cobra nada hoy. Te avisamos 1 día antes del primer cobro.',
    'plan_pill' => '🎁 7 días gratis · Hoy no se cobra nada',
    'plan_price' => 'MX$64',
    'plan_price_small' => '/ mes después de la prueba',
    'plan_feature_1' => 'Eventos ilimitados desde WhatsApp',
    'plan_feature_2' => 'Recordatorios automáticos',
    'plan_feature_3' => 'Sync con Google Calendar',
    'plan_feature_4' => 'Cancela cuando quieras',
    'campo_numero_tarjeta' => 'Número de tarjeta',
    'campo_vencimiento' => 'Vencimiento',
    'campo_cvc' => 'CVC',
    'campo_nombre_tarjeta' => 'Nombre en la tarjeta',
    'botao_empezar_prueba' => 'Empezar mi prueba gratis',
    'pago_trust' => '🔒 Pago seguro con Stripe · Te avisamos 1 día antes de cualquier cobro',

    'google_step_label' => 'Paso 3 de 4 · Google Calendar',
    'google_titulo' => 'Conecta tu Google Calendar',
    'google_subtitulo' => 'Aquí es donde tu asistente guarda y lee tus eventos. Sin esto, no hay magia. ✨',
    'google_titulo_desktop' => 'Casi listo 📅',
    'google_subtitulo_desktop' => 'Conecta tu calendario para que tu asistente trabaje por ti.',
    'google_perm_1' => 'Ver tus eventos para responder "¿qué tengo hoy?"',
    'google_perm_2' => 'Crear y editar eventos que tú pidas por WhatsApp',
    'google_perm_3' => 'Nunca leemos tu correo ni tus archivos',
    'botao_conectar_google' => 'Conectar con Google',
    'google_microlegal' => 'Te llevaremos a Google y regresarás aquí en segundos.',

    'whatsapp_step_label' => 'Paso 4 de 4 · WhatsApp',
    'whatsapp_titulo' => '¿A qué número te escribimos?',
    'whatsapp_subtitulo' => 'Tu asistente solo responde a este número. Es tu línea directa.',
    'whatsapp_titulo_desktop' => 'El último paso: tu WhatsApp',
    'whatsapp_subtitulo_desktop' => 'Tu asistente solo responde a tu número. Es tu línea directa, privada y segura.',
    'campo_whatsapp' => 'Tu número de WhatsApp',
    'whatsapp_aviso' => 'Te mandaremos un mensaje de bienvenida para confirmar. 🎉',
    'botao_conectar_whatsapp' => 'Conectar mi WhatsApp',
    'whatsapp_feature_1' => 'Mensaje de bienvenida al instante',
    'whatsapp_feature_2' => 'Funciona en WhatsApp normal y Business',
    'whatsapp_sep' => 'o si prefieres',
    'whatsapp_qr_titulo' => 'Escanéa y empieza a chatear',
    'whatsapp_qr_texto' => 'Abre la cámara, escanea el código y tu asistente te saluda al instante.',

    'home_saludo' => '¡Hola, Mariana! 👋',
    'home_subtitulo' => 'Todo listo. Tu agenda se maneja sola.',
    'badge_prueba_dias' => '🎁 Prueba · 5 días restantes',
    'assist_titulo' => 'Escríbele a tu asistente',
    'assist_ejemplo' => '"Agéndame el dentista el jueves a las 4"',
    'botao_abrir' => 'Abrir',
    'botao_abrir_whatsapp' => 'Abrir WhatsApp',
    'home_conexiones_titulo' => 'Tus conexiones',
    'home_eventos_titulo' => 'Próximos eventos',
    'home_google_label' => 'Google Calendar',
    'home_whatsapp_label' => 'WhatsApp',
    'home_conectado' => 'Conectado',
    'home_activo' => 'Activo',
    'home_pendiente' => 'Pendiente',
    'home_sin_eventos' => 'Aún no tienes eventos próximos. Pídele a tu asistente que agende uno por WhatsApp.',
    'home_micro_note' => '😉 Para crear o cambiar eventos, solo escríbele a tu asistente por WhatsApp.',
    'home_semana_titulo' => 'Esta semana',
    'home_semana_eventos' => 'eventos',
    'home_semana_recordatorios' => 'recordatorios',

    'menu_inicio' => 'Inicio',
    'menu_cuenta' => 'Mi cuenta',
    'menu_whatsapp' => 'Abrir WhatsApp',
    'badge_prueba' => '🎁 Prueba',
    'upgrade_titulo' => '🎁 Prueba gratis',
    'upgrade_texto' => 'Te quedan 5 días. Activa tu plan para no perder a tu asistente.',
    'upgrade_botao' => 'Ver mi plan',

    'conta_titulo' => 'Mi cuenta',
    'conta_suscripcion_titulo' => 'Suscripción',
    'plan_mensual' => 'Plan mensual',
    'plan_mensual_precio' => 'MX$64 /mes',
    'sub_dates' => 'Prueba gratis hasta el <b>17 jun</b>.<br>Primer cobro: <b>18 jun 2026</b>.',
    'botao_cambiar_tarjeta' => 'Cambiar tarjeta',
    'botao_cancelar_plan' => 'Cancelar plan',
    'preferencias_titulo' => 'Preferencias del asistente',
    'modo_silencio_titulo' => 'Modo silencio',
    'modo_silencio_sub' => 'No te escribimos de 10 pm a 7 am',
    'recordatorios_titulo' => 'Recordatorios',
    'recordatorios_sub' => 'Con cuánta antelación te avisamos',
    'recordatorio_15' => '15 min',
    'recordatorio_30' => '30 min',
    'recordatorio_1h' => '1 hora',
    'recordatorio_1d' => '1 día',
    'conexiones_titulo' => 'Conexiones',
    'botao_cambiar' => 'Cambiar',
    'botao_desconectar' => 'Desconectar',
    'sesion_titulo' => 'Sesión',
    'botao_cerrar_sesion' => 'Cerrar sesión',
];
