<?php

return [
    'erro_login_invalido' => 'E-mail ou senha incorretos.',
    'erro_email_existente' => 'Já existe uma conta com este e-mail.',
    'erro_campos_invalidos' => 'Por favor, preencha todos os campos corretamente.',

    'login_saudacao' => 'Olá de novo! 👋',
    'login_subtitulo' => 'Seu assistente estava com saudades.',
    'login_titulo' => 'Entrar',
    'campo_email' => 'E-mail',
    'campo_senha' => 'Senha',
    'senha_placeholder' => 'Sua senha',
    'link_esqueceu_senha' => 'Esqueceu sua senha?',
    'botao_entrar' => 'Entrar',
    'login_sem_conta' => 'Ainda não tem conta?',
    'link_criar_conta' => 'Crie uma grátis',
    'login_headline_desktop' => 'Sua agenda, direto no WhatsApp 📅',
    'login_subtitulo_desktop' => 'Diga ao seu assistente o que você precisa e pronto. Sem apps extras, sem complicação.',
    'login_feature_1' => 'Agende por mensagem, como com um amigo',
    'login_feature_2' => 'Lembretes automáticos na hora certa',
    'login_feature_3' => 'Sincronizado com seu Google Calendar',
    'login_social_proof' => '+2.000 pessoas já organizam sua vida',

    'botao_iniciar_sesion' => 'Entrar',
    'botao_atras' => 'Voltar',
    'botao_continuar' => 'Continuar',

    'cadastro_step_label' => 'Passo 1 de 4 · Sua conta',
    'cadastro_titulo' => 'Crie sua conta',
    'cadastro_subtitulo' => 'Em menos de 2 minutos sua agenda vive no WhatsApp.',
    'campo_nombre' => 'Seu nome',
    'campo_senha_minima' => 'Mínimo 8 caracteres',
    'hint_senha' => 'Use ao menos 8 caracteres.',
    'cadastro_microlegal' => 'Ao continuar você aceita os <a class="link" href="#">Termos</a> e o <a class="link" href="#">Aviso de privacidade</a>.',
    'cadastro_headline_desktop' => 'Comece grátis em 2 minutos',
    'cadastro_subtitulo_desktop' => 'Crie sua conta e deixe seu assistente cuidar da sua agenda.',
    'cadastro_feature_1' => '7 dias grátis, sem cartão para testar',
    'cadastro_feature_2' => 'Cancele quando quiser',
    'cadastro_feature_3' => 'Feito para o Brasil 🇧🇷',

    'pago_step_label' => 'Passo 2 de 4 · Pagamento',
    'pago_titulo' => 'Ative seu teste',
    'pago_subtitulo_desktop' => 'Nada é cobrado hoje. Avisamos 1 dia antes da primeira cobrança.',
    'plan_pill' => '🎁 7 dias grátis · Hoje não cobramos nada',
    'plan_price' => 'R$64',
    'plan_price_small' => '/ mês após o teste',
    'plan_feature_1' => 'Eventos ilimitados pelo WhatsApp',
    'plan_feature_2' => 'Lembretes automáticos',
    'plan_feature_3' => 'Sincronização com Google Calendar',
    'plan_feature_4' => 'Cancele quando quiser',
    'campo_numero_tarjeta' => 'Número do cartão',
    'campo_vencimiento' => 'Validade',
    'campo_cvc' => 'CVC',
    'campo_nombre_tarjeta' => 'Nome no cartão',
    'botao_empezar_prueba' => 'Começar meu teste grátis',
    'pago_trust' => '🔒 Pagamento seguro com Stripe · Avisamos 1 dia antes de qualquer cobrança',

    'google_step_label' => 'Passo 3 de 4 · Google Calendar',
    'google_titulo' => 'Conecte seu Google Calendar',
    'google_subtitulo' => 'Aqui é onde seu assistente guarda e lê seus eventos. Sem isso, não tem mágica. ✨',
    'google_titulo_desktop' => 'Quase lá 📅',
    'google_subtitulo_desktop' => 'Conecte seu calendário para seu assistente trabalhar por você.',
    'google_perm_1' => 'Ver seus eventos para responder "o que eu tenho hoje?"',
    'google_perm_2' => 'Criar e editar eventos que você pedir pelo WhatsApp',
    'google_perm_3' => 'Nunca lemos seu e-mail ou seus arquivos',
    'botao_conectar_google' => 'Conectar com Google',
    'google_microlegal' => 'Vamos te levar ao Google e você volta aqui em segundos.',

    'whatsapp_step_label' => 'Passo 4 de 4 · WhatsApp',
    'whatsapp_titulo' => 'Para qual número escrevemos?',
    'whatsapp_subtitulo' => 'Seu assistente só responde a este número. É sua linha direta.',
    'whatsapp_titulo_desktop' => 'O último passo: seu WhatsApp',
    'whatsapp_subtitulo_desktop' => 'Seu assistente só responde ao seu número. É sua linha direta, privada e segura.',
    'campo_whatsapp' => 'Seu número de WhatsApp',
    'whatsapp_aviso' => 'Vamos te enviar uma mensagem de boas-vindas para confirmar. 🎉',
    'botao_conectar_whatsapp' => 'Conectar meu WhatsApp',
    'whatsapp_feature_1' => 'Mensagem de boas-vindas instantânea',
    'whatsapp_feature_2' => 'Funciona no WhatsApp normal e Business',
    'whatsapp_sep' => 'ou se preferir',
    'whatsapp_qr_titulo' => 'Escaneie e comece a conversar',
    'whatsapp_qr_texto' => 'Abra a câmera, escaneie o código e seu assistente te saúda na hora.',

    'home_saludo' => 'Olá, Mariana! 👋',
    'home_subtitulo' => 'Tudo certo. Sua agenda se cuida sozinha.',
    'badge_prueba_dias' => '🎁 Teste · 5 dias restantes',
    'assist_titulo' => 'Escreva para seu assistente',
    'assist_ejemplo' => '"Marca o dentista na quinta às 16h"',
    'botao_abrir' => 'Abrir',
    'botao_abrir_whatsapp' => 'Abrir WhatsApp',
    'home_conexiones_titulo' => 'Suas conexões',
    'home_eventos_titulo' => 'Próximos eventos',
    'home_google_label' => 'Google Calendar',
    'home_whatsapp_label' => 'WhatsApp',
    'home_conectado' => 'Conectado',
    'home_activo' => 'Ativo',
    'home_pendiente' => 'Pendente',
    'home_sin_eventos' => 'Você ainda não tem eventos próximos. Peça ao seu assistente para agendar um pelo WhatsApp.',
    'home_micro_note' => '😉 Para criar ou mudar eventos, basta escrever para seu assistente no WhatsApp.',
    'home_semana_titulo' => 'Esta semana',
    'home_semana_eventos' => 'eventos',
    'home_semana_recordatorios' => 'lembretes',

    'menu_inicio' => 'Início',
    'menu_cuenta' => 'Minha conta',
    'menu_whatsapp' => 'Abrir WhatsApp',
    'badge_prueba' => '🎁 Teste',
    'upgrade_titulo' => '🎁 Teste grátis',
    'upgrade_texto' => 'Faltam 5 dias. Ative seu plano para não perder seu assistente.',
    'upgrade_botao' => 'Ver meu plano',

    'conta_titulo' => 'Minha conta',
    'conta_suscripcion_titulo' => 'Assinatura',
    'plan_mensual' => 'Plano mensal',
    'plan_mensual_precio' => 'R$64 /mês',
    'sub_dates' => 'Teste grátis até <b>17 jun</b>.<br>Primeira cobrança: <b>18 jun 2026</b>.',
    'botao_cambiar_tarjeta' => 'Mudar cartão',
    'botao_cancelar_plan' => 'Cancelar plano',
    'preferencias_titulo' => 'Preferências do assistente',
    'modo_silencio_titulo' => 'Modo silêncio',
    'modo_silencio_sub' => 'Não escrevemos das 22h às 7h',
    'recordatorios_titulo' => 'Lembretes',
    'recordatorios_sub' => 'Com quanta antecedência avisamos',
    'recordatorio_15' => '15 min',
    'recordatorio_30' => '30 min',
    'recordatorio_1h' => '1 hora',
    'recordatorio_1d' => '1 dia',
    'conexiones_titulo' => 'Conexões',
    'botao_cambiar' => 'Mudar',
    'botao_desconectar' => 'Desconectar',
    'sesion_titulo' => 'Sessão',
    'botao_cerrar_sesion' => 'Encerrar sessão',
];
