<?php

return [
    'erro_login_invalido' => 'E-mail ou senha incorretos.',
    'erro_email_existente' => 'Já existe uma conta com este e-mail.',
    'erro_campos_invalidos' => 'Por favor, preencha todos os campos corretamente.',
    'erro_senha_fraca' => 'A senha deve ter ao menos 8 caracteres, com maiúscula, minúscula, número e caractere especial.',
    'erro_senha_confirmacao' => 'As senhas não coincidem.',

    'login_saudacao' => 'Olá de novo! 👋',
    'login_subtitulo' => 'Seu assistente estava com saudades.',
    'login_titulo' => 'Entrar',
    'campo_email' => 'E-mail',
    'email_placeholder' => 'voce@email.com',
    'nome_placeholder' => 'Mariana',
    'campo_senha' => 'Senha',
    'senha_placeholder' => 'Sua senha',
    'link_esqueceu_senha' => 'Esqueceu sua senha?',

    'recuperar_titulo' => 'Recuperar senha',
    'recuperar_subtitulo' => 'Digite seu email e enviaremos instruções para redefinir sua senha.',
    'recuperar_titulo_desktop' => 'Recupere seu acesso',
    'recuperar_subtitulo_desktop' => 'Enviaremos um link seguro para você criar uma nova senha.',
    'recuperar_botao' => 'Enviar link de recuperação',
    'recuperar_email_enviado' => 'Se este email estiver cadastrado, você receberá as instruções em breve.',
    'recuperar_voltar_login' => 'Voltar para o login',

    'redefinir_titulo' => 'Nova senha',
    'redefinir_titulo_desktop' => 'Crie sua nova senha',
    'redefinir_subtitulo_desktop' => 'Escolha uma senha forte e segura.',
    'redefinir_botao' => 'Salvar nova senha',
    'redefinir_senha_atualizada' => 'Senha atualizada com sucesso! Faça login com sua nova senha.',
    'redefinir_token_invalido' => 'Link inválido ou expirado. Solicite um novo.',
    'redefinir_pedir_novo' => 'Solicitar novo link',

    'email_recuperacao_assunto' => 'Recuperação de senha — %s',
    'email_recuperacao_corpo' => '<div style="font-family:sans-serif;max-width:480px;margin:0 auto;padding:24px;"><h2>Olá, %s!</h2><p>Recebemos um pedido para redefinir sua senha.</p><p><a href="%s" style="display:inline-block;padding:12px 24px;background:#3b82f6;color:#fff;text-decoration:none;border-radius:8px;font-weight:bold;">Redefinir minha senha</a></p><p style="font-size:13px;color:#666;">Se não foi você, ignore este email. O link expira em 1 hora.</p><p style="font-size:13px;color:#666;">Ou copie e cole: %s</p><hr style="border:none;border-top:1px solid #eee;margin:24px 0;"><p style="font-size:12px;color:#999;">%s</p></div>',

    'admin_email_remetente' => 'Email remetente',
    'admin_email_remetente_desc' => 'Email usado como remetente nos emails do sistema (recuperação de senha, etc)',
    'botao_entrar' => 'Entrar',
    'botao_google_login' => 'Entrar com Google',
    'botao_google_cadastro' => 'Cadastrar com Google',
    'erro_google_login' => 'Não foi possível autenticar com Google. Tente novamente.',
    'divisor_ou' => 'ou',
    'login_sem_conta' => 'Ainda não tem conta?',
    'link_criar_conta' => 'Crie uma grátis',
    'cadastro_ja_tem_conta' => 'Já tem uma conta?',
    'link_iniciar_sesion' => 'Entrar',
    'login_headline_desktop' => 'Sua agenda, direto no WhatsApp 📅',
    'login_subtitulo_desktop' => 'Diga ao seu assistente o que você precisa e pronto. Sem apps extras, sem complicação.',
    'login_feature_1' => 'Agende por mensagem, como com um amigo',
    'login_feature_2' => 'Lembretes automáticos na hora certa',
    'login_feature_3' => 'Sincronizado com seu Google Calendar',
    'login_social_proof' => '+2.000 pessoas já organizam sua vida',

    'botao_iniciar_sesion' => 'Entrar',
    'botao_atras' => 'Voltar',
    'botao_continuar' => 'Continuar',

    'cadastro_step_label' => 'Passo 1 de 4 · Sua conta',
    'cadastro_titulo' => 'Crie sua conta',
    'cadastro_subtitulo' => 'Em menos de 2 minutos sua agenda vive no WhatsApp.',
    'campo_nombre' => 'Seu nome',
    'campo_senha_minima' => 'Mínimo 8 caracteres',
    'hint_senha' => 'Mínimo 8 caracteres, com maiúscula, minúscula, número e caractere especial.',
    'senha_mostrar' => 'Mostrar senha',
    'campo_confirmar_senha' => 'Confirmar senha',
    'senha_confirmar_placeholder' => 'Repita sua senha',
    'cadastro_microlegal' => 'Ao continuar você aceita os <a class="link" href="#">Termos</a> e o <a class="link" href="#">Aviso de privacidade</a>.',
    'cadastro_headline_desktop' => 'Comece em 2 minutos',
    'cadastro_subtitulo_desktop' => 'Crie sua conta e deixe seu assistente cuidar da sua agenda.',
    'cadastro_feature_1' => 'Configuração rápida e simples',
    'cadastro_feature_2' => 'Cancele quando quiser',
    'cadastro_feature_3' => 'Feito para o Brasil 🇧🇷',

    'pago_step_label' => 'Passo 2 de 4 · Pagamento',
    'pago_titulo' => 'Ative seu plano',
    'pago_subtitulo_desktop' => 'Pagamento seguro e rápido. Cancele quando quiser.',
    'plan_pill' => '✨ Seu plano',
    'plan_price' => 'R$64',
    'plan_price_small' => '/ mês',
    'plan_feature_1' => 'Eventos ilimitados pelo WhatsApp',
    'plan_feature_2' => 'Lembretes automáticos',
    'plan_feature_3' => 'Sincronização com Google Calendar',
    'plan_feature_4' => 'Cancele quando quiser',
    'campo_numero_tarjeta' => 'Número do cartão',
    'campo_vencimiento' => 'Validade',
    'campo_cvc' => 'CVC',
    'campo_nombre_tarjeta' => 'Nome no cartão',
    'botao_empezar_prueba' => 'Assinar agora',
    'pago_trust' => '🔒 Pagamento seguro com Stripe · Avisamos 1 dia antes de qualquer cobrança',
    'pago_botao_checkout' => 'Continuar para o pagamento',
    'pago_cancelado' => 'Pagamento cancelado. Tente novamente.',
    'pago_erro_plano' => 'Plano não configurado para pagamento. Contate o suporte.',
    'pago_erro_stripe' => 'Erro ao processar pagamento. Tente novamente.',
    'pago_processando' => 'Processando...',
    'pago_escolha_plano' => 'Escolha seu plano',
    'pago_escolha_subtitulo' => 'Selecione o plano ideal para você.',
    'pago_botao_escolher' => 'Escolher este plano',
    'pago_dias_teste' => '🎁 %d dias grátis para testar',
    'pago_marca_titulo' => 'Escolha e comece agora',
    'pago_marca_subtitulo' => 'Planos flexíveis, cancele quando quiser.',

    'google_step_label' => 'Passo 3 de 4 · Google Calendar',
    'google_titulo' => 'Conecte seu Google Calendar',
    'google_subtitulo' => 'Aqui é onde seu assistente guarda e lê seus eventos. Sem isso, não tem mágica. ✨',
    'google_titulo_desktop' => 'Quase lá 📅',
    'google_subtitulo_desktop' => 'Conecte seu calendário para seu assistente trabalhar por você.',
    'google_perm_1' => 'Ver seus eventos para responder "o que eu tenho hoje?"',
    'google_perm_2' => 'Criar e editar eventos que você pedir pelo WhatsApp',
    'google_perm_3' => 'Nunca lemos seu e-mail ou seus arquivos',
    'botao_conectar_google' => 'Conectar com Google',
    'google_microlegal' => 'Vamos te levar ao Google e você volta aqui em segundos.',

    'whatsapp_step_label' => 'Passo 4 de 4 · WhatsApp',
    'whatsapp_titulo' => 'Para qual número escrevemos?',
    'whatsapp_subtitulo' => 'Seu assistente só responde a este número. É sua linha direta.',
    'whatsapp_titulo_desktop' => 'O último passo: seu WhatsApp',
    'whatsapp_subtitulo_desktop' => 'Seu assistente só responde ao seu número. É sua linha direta, privada e segura.',
    'campo_whatsapp' => 'Seu número de WhatsApp',
    'whatsapp_aviso' => 'Vamos te enviar uma mensagem de boas-vindas para confirmar. 🎉',
    'botao_conectar_whatsapp' => 'Conectar meu WhatsApp',
    'whatsapp_feature_1' => 'Mensagem de boas-vindas instantânea',
    'whatsapp_feature_2' => 'Funciona no WhatsApp normal e Business',
    'whatsapp_sep' => 'ou se preferir',
    'whatsapp_qr_titulo' => 'Escaneie e comece a conversar',
    'whatsapp_qr_texto' => 'Abra a câmera, escaneie o código e seu assistente te saúda na hora.',

    'home_saludo' => 'Olá, Mariana! 👋',
    'home_subtitulo' => 'Tudo certo. Sua agenda se cuida sozinha.',
    'badge_prueba_dias' => '🎁 Teste · 5 dias restantes',
    'badge_ativo' => '✅ Ativo',
    'badge_expirado' => '⚠️ Expirado',
    'assist_titulo' => 'Escreva para seu assistente',
    'assist_ejemplo' => '"Marca o dentista na quinta às 16h"',
    'botao_abrir' => 'Abrir',
    'botao_abrir_whatsapp' => 'Abrir WhatsApp',
    'home_conexiones_titulo' => 'Suas conexões',
    'home_eventos_titulo' => 'Próximos eventos',
    'home_google_label' => 'Google Calendar',
    'home_whatsapp_label' => 'WhatsApp',
    'home_conectado' => 'Conectado',
    'home_activo' => 'Ativo',
    'home_pendiente' => 'Pendente',
    'home_sin_eventos' => 'Você ainda não tem eventos próximos. Peça ao seu assistente para agendar um pelo WhatsApp.',
    'home_micro_note' => '😉 Para criar ou mudar eventos, basta escrever para seu assistente no WhatsApp.',
    'home_semana_titulo' => 'Esta semana',
    'home_semana_eventos' => 'eventos',
    'home_semana_recordatorios' => 'lembretes',

    'menu_inicio' => 'Início',
    'menu_cuenta' => 'Minha conta',
    'menu_whatsapp' => 'Abrir WhatsApp',
    'menu_salir' => 'Sair',
    'badge_prueba' => '🎁 Teste',
    'upgrade_botao' => 'Ativar plano',
    'upgrade_ciclo_mensal' => '/ mês',
    'upgrade_ciclo_trimestral' => '/ trimestre',
    'upgrade_ciclo_anual' => '/ ano',

    'conta_titulo' => 'Minha conta',
    'conta_suscripcion_titulo' => 'Assinatura',
    'plan_mensual' => 'Plano mensal',
    'plan_mensual_precio' => 'R$64 /mês',
    'sub_dates' => '',
    'sub_dates_dinamico' => 'Próxima cobrança: <b>%s</b>',
    'botao_cambiar_tarjeta' => 'Mudar cartão',
    'botao_cancelar_plan' => 'Cancelar plano',
    'preferencias_titulo' => 'Preferências do assistente',
    'modo_silencio_titulo' => 'Modo silêncio',
    'modo_silencio_sub' => 'Não escrevemos das 22h às 7h',
    'recordatorios_titulo' => 'Lembretes',
    'recordatorios_sub' => 'Com quanta antecedência avisamos',
    'recordatorio_15' => '15 min',
    'recordatorio_30' => '30 min',
    'recordatorio_1h' => '1 hora',
    'recordatorio_1d' => '1 dia',
    'conexiones_titulo' => 'Conexões',
    'botao_cambiar' => 'Mudar',
    'botao_desconectar' => 'Desconectar',
    'sesion_titulo' => 'Sessão',
    'botao_cerrar_sesion' => 'Encerrar sessão',

    // Admin — Sidebar
    'admin_menu' => 'Menu',
    'admin_dashboard' => 'Dashboard',
    'admin_usuarios' => 'Usuários',
    'admin_configuracao' => 'Configuração',
    'admin_sair' => 'Sair',

    // Admin — Login
    'admin_painel' => 'Painel administrativo',
    'admin_entrar' => 'Entrar',
    'admin_acesse_painel' => 'Acesse o painel de gerenciamento.',
    'admin_email' => 'E-mail',
    'admin_senha' => 'Senha',
    'admin_sua_senha' => 'Sua senha',
    'admin_login_erro' => 'E-mail ou senha incorretos.',

    // Admin — Dashboard
    'admin_visao_geral' => 'Visão geral do sistema',
    'admin_total_usuarios' => 'Total de usuários',
    'admin_usuarios_ativos' => 'Usuários ativos',
    'admin_eventos_criados' => 'Eventos criados',
    'admin_mensagens_trocadas' => 'Mensagens trocadas',
    'admin_em_trial' => 'Em trial',
    'admin_plano_ativo' => 'Plano ativo',
    'admin_cancelados' => 'Cancelados',
    'admin_eventos_hoje' => 'Eventos hoje',
    'dash_receita_estimada' => 'Receita estimada',
    'dash_assinantes' => 'assinantes ativos',
    'dash_conversao' => 'Taxa de conversão',
    'dash_trial_para_ativo' => 'trial → ativo',
    'dash_novos_semana' => 'Novos esta semana',
    'dash_este_mes' => 'este mês',
    'dash_ativos' => 'ativos',
    'dash_hoje' => 'hoje',
    'dash_grafico_atividade' => 'Atividade (últimos 30 dias)',
    'dash_grafico_planos' => 'Distribuição de planos',
    'dash_leg_usuarios' => 'Novos usuários',
    'dash_leg_eventos' => 'Eventos',
    'dash_leg_mensagens' => 'Mensagens',
    'dash_inativos' => 'Inativos',
    'dash_cancelamentos' => 'Cancelamentos',
    'dash_grafico_receita' => 'Receita por mês',
    'dash_grafico_usuarios' => 'Novos usuários vs Cancelamentos (30 dias)',
    'dash_resumo' => 'Resumo operacional',
    'admin_eventos_recentes' => 'Eventos recentes',
    'admin_titulo' => 'Título',
    'admin_usuario' => 'Usuário',
    'admin_data' => 'Data',
    'admin_lembrete' => 'Lembrete',
    'admin_enviado' => 'Enviado',
    'admin_pendente' => 'Pendente',
    'admin_nenhum_evento' => 'Nenhum evento registrado ainda.',

    // Admin — Usuários
    'admin_usuario_encontrado' => 'usuário encontrado',
    'admin_usuarios_encontrados' => 'usuários encontrados',
    'admin_novo_usuario' => 'Novo usuário',
    'admin_lista_usuarios' => 'Lista de usuários',
    'admin_nome' => 'Nome',
    'admin_email_col' => 'E-mail',
    'admin_telefone' => 'Telefone',
    'admin_plano' => 'Plano',
    'admin_status' => 'Status',
    'admin_cadastro' => 'Cadastro',
    'admin_acoes' => 'Ações',
    'admin_ativo' => 'Ativo',
    'admin_inativo' => 'Inativo',
    'admin_ativar' => 'Ativar',
    'admin_desativar' => 'Desativar',
    'admin_apagar' => 'Apagar',
    'admin_confirmar_apagar' => 'Tem certeza que deseja apagar este usuário?',
    'admin_editar' => 'Editar',
    'admin_buscar' => 'Buscar por nome, e-mail...',
    'admin_todos_planos' => 'Todos os planos',
    'admin_nenhum_usuario' => 'Nenhum usuário encontrado.',
    'admin_nome_completo' => 'Nome completo',
    'admin_min_senha' => 'Mínimo 6 caracteres',
    'admin_expiracao_plano' => 'Expiração do plano',
    'admin_cancelar' => 'Cancelar',
    'admin_criar_usuario' => 'Criar usuário',
    'admin_editar_usuario' => 'Editar usuário',
    'admin_salvar' => 'Salvar alterações',
    'admin_usuario_criado' => 'Usuário criado com sucesso.',
    'admin_usuario_atualizado' => 'Usuário atualizado com sucesso.',
    'admin_usuario_ativado' => 'Usuário ativado.',
    'admin_usuario_desativado' => 'Usuário desativado.',
    'admin_usuario_apagado' => 'Usuário apagado com sucesso.',
    'admin_erro_campos' => 'Nome, e-mail e senha são obrigatórios.',
    'admin_erro_senha_curta' => 'A senha deve ter pelo menos 6 caracteres.',
    'admin_erro_email_existe' => 'Já existe um usuário com este e-mail.',
    'admin_erro_email_outro' => 'Já existe outro usuário com este e-mail.',
    'admin_erro_nome_email' => 'Nome e e-mail são obrigatórios.',
    'admin_erro_telefone_existe' => 'Já existe um usuário com este número de telefone.',
    'admin_erro_telefone_outro' => 'Já existe outro usuário com este número de telefone.',
    'erro_telefone_existe' => 'Este número de WhatsApp já está registrado em outra conta.',

    // Admin — Configuração
    'admin_config_subtitulo' => 'Variáveis de ambiente e estado do sistema',
    'admin_preferencias' => 'Preferências',
    'admin_idioma' => 'Idioma',
    'admin_idioma_desc' => 'Idioma padrão da interface',
    'admin_fuso_horario' => 'Fuso horário',
    'admin_fuso_desc' => 'Fuso horário padrão para novos usuários',
    'admin_salvar_prefs' => 'Salvar preferências',
    'admin_prefs_salvas' => 'Preferências salvas com sucesso.',
    'admin_confirmar_titulo' => 'Confirmar alteração',
    'admin_confirmar_texto' => 'Estas são configurações críticas do sistema. Para confirmar, digite a palavra abaixo.',
    'admin_confirmar_label' => 'Digite CONFIRMAR para prosseguir',
    'admin_confirmar_placeholder' => 'CONFIRMAR',
    'admin_confirmar_palavra' => 'CONFIRMAR',
    'admin_confirmar_salvar' => 'Salvar alterações',
    'admin_geral' => 'Geral',
    'admin_moeda' => 'Moeda',
    'admin_moeda_desc' => 'Moeda usada nos preços e na cobrança',
    'admin_nome_app' => 'Nome do aplicativo',
    'admin_nome_app_desc' => 'Exibido em todo o sistema (títulos, sidebar, landpage, etc)',
    'admin_contato_redes' => 'Contato e redes sociais',
    'admin_link_suporte' => 'Link de suporte',
    'admin_link_suporte_desc' => 'Link exibido como "Suporte" no rodapé',
    'admin_email_suporte' => 'E-mail de contato',
    'admin_email_suporte_desc' => 'Exibido no rodapé da landing page',
    'admin_instagram_desc' => 'Usuário do Instagram (com ou sem @)',
    'admin_tiktok_desc' => 'Usuário do TikTok (com ou sem @)',
    'admin_variaveis' => 'Variáveis de ambiente',
    'admin_sistema' => 'Sistema',
    'admin_php_versao' => 'Versão do interpretador',
    'admin_servidor' => 'Servidor',
    'admin_servidor_desc' => 'Software do servidor web',
    'admin_modo_dev' => 'Modo dev',
    'admin_modo_dev_desc' => 'Simulações e bypass ativados',
    'admin_ativado' => 'Ativado',
    'admin_desativado' => 'Desativado',

    // Admin — Planos
    'admin_planos' => 'Planos',
    'admin_planos_subtitulo' => 'Gerencie os planos disponíveis',
    'admin_novo_plano' => 'Novo plano',
    'admin_lista_planos' => 'Lista de planos',
    'admin_plano_encontrado' => 'plano encontrado',
    'admin_planos_encontrados' => 'planos encontrados',
    'admin_nome_plano' => 'Nome do plano',
    'admin_descricao' => 'Descrição',
    'admin_descricao_placeholder' => 'Breve descrição do plano',
    'admin_ciclo' => 'Ciclo',
    'admin_mensal' => 'Mensal',
    'admin_trimestral' => 'Trimestral',
    'admin_anual' => 'Anual',
    'admin_preco' => 'Preço',
    'admin_dias_teste' => 'Dias de teste',
    'admin_dias_teste_hint' => '0 = sem período de teste',
    'admin_etiqueta_texto' => 'Etiqueta',
    'admin_etiqueta_placeholder' => 'Ex: Popular, Preço de lançamento',
    'admin_etiqueta_hint' => 'Texto exibido no selo do card. Vazio = padrão automático.',
    'admin_stripe_price_hint' => 'ID do preço no Stripe (ex: price_1Abc...). Copie do Dashboard do Stripe.',
    'admin_etiqueta_cor' => 'Cor da etiqueta',
    'admin_cor_amarelo' => 'Amarelo',
    'admin_cor_azul' => 'Azul',
    'admin_cor_verde' => 'Verde',
    'admin_cor_vermelho' => 'Vermelho',
    'admin_cor_roxo' => 'Roxo',
    'admin_todos_ciclos' => 'Todos os ciclos',
    'admin_nenhum_plano' => 'Nenhum plano cadastrado.',
    'admin_criar_plano' => 'Criar plano',
    'admin_editar_plano' => 'Editar plano',
    'admin_plano_criado' => 'Plano criado com sucesso.',
    'admin_plano_atualizado' => 'Plano atualizado com sucesso.',
    'admin_plano_ativado' => 'Plano ativado.',
    'admin_plano_desativado' => 'Plano desativado.',
    'admin_plano_excluido' => 'Plano excluído.',
    'admin_erro_nome_preco' => 'Nome e preço são obrigatórios.',
    'admin_excluir' => 'Excluir',
    'admin_teste' => 'teste',
    'admin_dias' => 'dias',
    'admin_sem_teste' => 'Sem teste',

    // Landing page
    'lp_title' => '%APP% — Sua agenda no WhatsApp',
    'lp_login' => 'Entrar',
    'lp_hero_h1' => 'Sua agenda, direto<br>no WhatsApp',
    'lp_hero_lead' => 'Diga ao seu assistente o que você precisa e pronto. Sem apps extras, sem complicação.',
    'lp_hero_cta' => 'Testar grátis %d dias',
    'lp_hero_cta_sem_teste' => 'Começar agora',
    'lp_hero_micro' => 'Sem cartão · Cancele quando quiser',
    'lp_hero_micro_sem_teste' => 'Cancele quando quiser',
    'lp_hero_social' => '+2.000 pessoas já organizam sua vida',
    'lp_how_eyebrow' => 'Simples assim',
    'lp_how_title' => 'Como funciona?',
    'lp_how_sub' => 'Três passos e sua vida se organiza sozinha.',
    'lp_step1_title' => 'Conecte-se em segundos',
    'lp_step1_text' => 'Cadastre seu número e comece a conversar. Sem instalar nada.',
    'lp_step2_title' => 'Escreva como para um amigo',
    'lp_step2_text' => '"Marca o dentista na quinta às 16h." Ele entende e agenda.',
    'lp_step3_title' => 'Avisamos na hora certa',
    'lp_step3_text' => 'Lembretes automáticos para você não perder nada.',
    'lp_demo_eyebrow' => 'Veja em ação',
    'lp_demo_title' => 'Fale. Ele organiza.',
    'lp_demo_sub' => 'Uma conversa normal. Só isso.',
    'lp_demo_online' => '● online',
    'lp_demo_note' => 'Funciona no mesmo WhatsApp que você já usa 💬',
    'lp_demo_me1' => 'Agenda uma consulta com o doutor amanhã às 11h',
    'lp_demo_them1' => '✅ Pronto, agendei sua consulta. Aviso 30 min antes.',
    'lp_demo_stamp1' => 'ter 13 jun · 11:00',
    'lp_demo_me2' => 'O que tenho essa semana?',
    'lp_demo_them2' => '📅 Você tem 3 eventos: médico, almoço com a mãe e conta de luz.',
    'lp_demo_stamp2' => 'esta semana',
    'lp_ben_eyebrow' => 'Por que você vai adorar',
    'lp_ben_title' => 'Feito para o seu dia a dia',
    'lp_ben1_title' => 'Sem instalar nada',
    'lp_ben1_text' => 'Vive no seu WhatsApp.',
    'lp_ben2_title' => 'Sync com Google',
    'lp_ben2_text' => 'Conecta ao seu calendário.',
    'lp_ben3_title' => 'Lembretes auto',
    'lp_ben3_text' => 'Avisa antes de cada compromisso.',
    'lp_ben4_title' => 'Modo silêncio',
    'lp_ben4_text' => 'Respeita seu horário de descanso.',
    'lp_ben5_title' => 'Dados seguros',
    'lp_ben5_text' => 'Sua informação, protegida.',
    'lp_ben6_title' => 'Feito para o Brasil',
    'lp_ben6_flag' => '🇧🇷',
    'lp_ben6_text' => 'Fala sua língua e seu fuso.',
    'lp_price_eyebrow_single' => 'Um plano só, sem enrolação',
    'lp_price_eyebrow_multi' => 'Escolha seu plano',
    'lp_price_title' => 'Preço',
    'lp_price_default_name' => 'Plano %APP%',
    'lp_price_default_was' => 'antes <s>R$99</s> · economize 35%',
    'lp_price_tag_launch' => '🏆 Preço de lançamento',
    'lp_price_tag_trial' => '🎁 %d dias grátis',
    'lp_price_cta' => 'Começar teste grátis',
    'lp_price_cta_sem_teste' => 'Assinar agora',
    'lp_price_guarantee' => '🛡️ %d dias grátis · sem compromisso',
    'lp_feat1' => 'Agendamento por WhatsApp ilimitado',
    'lp_feat2' => 'Sincronização com Google Calendar',
    'lp_feat3' => 'Lembretes automáticos',
    'lp_feat4' => 'Modo silêncio personalizável',
    'lp_feat5' => 'Suporte via WhatsApp',
    'lp_faq_eyebrow' => 'Dúvidas?',
    'lp_faq_title' => 'Perguntas frequentes',
    'lp_faq1_q' => 'Preciso instalar alguma coisa?',
    'lp_faq1_a' => 'Não. O %APP% funciona dentro do WhatsApp, o app que você já tem. Só cadastrar seu número e pronto.',
    'lp_faq2_q' => 'Funciona com meu Google Calendar?',
    'lp_faq2_a' => 'Sim. Sincroniza com seu Google Calendar para tudo ficar num lugar só, na hora.',
    'lp_faq3_q' => 'O que acontece se eu cancelar?',
    'lp_faq3_a' => 'Cancela quando quiser, sem multa. Seus eventos continuam no seu calendário normal.',
    'lp_faq4_q' => 'Meus dados estão seguros?',
    'lp_faq4_a' => 'Sua informação é criptografada e nunca compartilhada. Só você e seu assistente têm acesso.',
    'lp_faq5_q' => 'Funciona em qualquer WhatsApp?',
    'lp_faq5_a' => 'Sim, funciona no WhatsApp normal e Business, no Android e iPhone.',
    'lp_final_title' => 'Comece a se organizar hoje 🚀',
    'lp_final_text' => 'Junte-se a milhares de pessoas que já deixaram o caos para trás com o %APP%.',
    'lp_final_cta' => 'Criar minha conta grátis',
    'lp_final_cta_sem_teste' => 'Criar minha conta',
    'lp_final_micro' => '%d dias grátis · Sem cartão · Cancele quando quiser',
    'lp_final_micro_sem_teste' => 'Cancele quando quiser',
    'lp_footer_copy' => '© %d %APP% · Feito com 💙 no Brasil',
    'lp_privacy' => 'Privacidade',
    'lp_terms' => 'Termos',
    'lp_support' => 'Suporte',
    'lp_contact' => 'Contato',
    'lp_ciclo_mensal' => '/mês',
    'lp_ciclo_trimestral' => '/trim',
    'lp_ciclo_anual' => '/ano',
    'lp_moeda' => 'R$',

    // Modais conta
    'modal_cambiar_plan' => 'Mudar de plano',
    'modal_cambiar_plan_sub' => 'Seu plano atual está marcado. A mudança vale no próximo ciclo.',
    'modal_plan_actual' => '✓ Plano atual',
    'modal_cambiar_a_este' => 'Mudar para este',
    'modal_facturacion' => 'Faturação',
    'modal_facturado_anual' => '%s cobrado ao ano',
    'modal_trust_plan' => '🔒 Pagamento seguro com Stripe · Mude ou cancele a qualquer momento',
    'modal_cambiar_tarjeta' => 'Mudar cartão',
    'modal_cambiar_tarjeta_sub' => 'Atualize o método de pagamento da sua assinatura.',
    'modal_num_tarjeta' => 'Número do cartão',
    'modal_vencimiento' => 'Validade',
    'modal_nombre_tarjeta' => 'Nome no cartão',
    'modal_guardar_tarjeta' => 'Salvar cartão',
    'modal_trust_tarjeta' => '🔒 Seus dados são processados com segurança via Stripe',
    'modal_cancelar_plan' => 'Cancelar seu plano?',
    'modal_cancelar_sub' => 'Seu assistente vai parar de organizar sua agenda ao fim do ciclo atual.',
    'modal_cancelar_alerta' => 'Se você ficar, mantém o agendamento ilimitado, lembretes e sincronização com o Google até',
    'modal_mantener' => 'Manter meu plano',
    'modal_si_cancelar' => 'Sim, cancelar plano',
    'modal_ahorra' => 'Economize %d%%',
    'modal_todo_del_plan' => 'Tudo do plano mensal',
    'modal_meses_gratis' => '2 meses grátis',
    'modal_precio_fijo' => 'Preço fixo o ano todo',

    // Menu — Finanças
    'menu_financas' => 'Finanças',

    // Finanças
    'fin_titulo' => 'Controle Financeiro',
    'fin_subtitulo' => 'Seu dinheiro, organizado sozinho. Registre tudo pelo WhatsApp.',
    'fin_saldo_mes' => 'Saldo do mês',
    'fin_vs_mes_anterior' => 'vs. %s',
    'fin_ingresos' => 'Entradas',
    'fin_gastos' => 'Saídas',
    'fin_gastos_categoria' => 'Saídas por categoria',
    'fin_distribucion' => 'Distribuição de %s - R$%s',
    'fin_grafico_titulo' => 'Entradas vs. Saídas',
    'fin_grafico_subtitulo' => 'Últimos 6 meses',
    'fin_transacoes_titulo' => 'TRANSAÇÕES RECENTES',
    'fin_novo' => '+ Novo',
    'fin_buscar' => 'Buscar transação ou categoria...',
    'fin_nota_whatsapp' => 'Para registrar uma saída ou entrada, basta escrever pro seu assistente: "Gastei 200 de gasolina".',
    'fin_sem_transacoes' => 'Nenhuma transação neste mês ainda.',
    'fin_modal_novo_titulo' => 'Nova transação',
    'fin_modal_editar_titulo' => 'Editar transação',
    'fin_campo_tipo' => 'Tipo',
    'fin_tipo_entrada' => 'Entrada',
    'fin_tipo_saida' => 'Saída',
    'fin_campo_valor' => 'Valor',
    'fin_campo_descricao' => 'Descrição',
    'fin_descricao_placeholder' => 'Ex: Salário quinzenal',
    'fin_campo_categoria' => 'Categoria',
    'fin_campo_data' => 'Data',
    'fin_botao_salvar' => 'Salvar',
    'fin_botao_cancelar' => 'Cancelar',
    'fin_botao_deletar' => 'Excluir',
    'fin_confirmar_deletar' => 'Excluir esta transação?',
    'fin_criada' => 'Transação registrada.',
    'fin_atualizada' => 'Transação atualizada.',
    'fin_deletada' => 'Transação excluída.',
    'fin_erro_campos' => 'Preencha todos os campos obrigatórios.',
    'fin_erro_valor' => 'O valor deve ser maior que 0.',
    'fin_cat_alimentacao' => 'Alimentação',
    'fin_cat_transporte' => 'Transporte',
    'fin_cat_entretenimento' => 'Entretenimento',
    'fin_cat_servicos' => 'Serviços',
    'fin_cat_saude' => 'Saúde',
    'fin_cat_educacao' => 'Educação',
    'fin_cat_moradia' => 'Moradia',
    'fin_cat_compras' => 'Compras',
    'fin_cat_salario' => 'Salário',
    'fin_cat_entrada' => 'Entrada',
    'fin_cat_outros' => 'Outros',
    'fin_mes_1' => 'Janeiro',
    'fin_mes_2' => 'Fevereiro',
    'fin_mes_3' => 'Março',
    'fin_mes_4' => 'Abril',
    'fin_mes_5' => 'Maio',
    'fin_mes_6' => 'Junho',
    'fin_mes_7' => 'Julho',
    'fin_mes_8' => 'Agosto',
    'fin_mes_9' => 'Setembro',
    'fin_mes_10' => 'Outubro',
    'fin_mes_11' => 'Novembro',
    'fin_mes_12' => 'Dezembro',
    'fin_mes_curto_1' => 'Jan',
    'fin_mes_curto_2' => 'Fev',
    'fin_mes_curto_3' => 'Mar',
    'fin_mes_curto_4' => 'Abr',
    'fin_mes_curto_5' => 'Mai',
    'fin_mes_curto_6' => 'Jun',
    'fin_mes_curto_7' => 'Jul',
    'fin_mes_curto_8' => 'Ago',
    'fin_mes_curto_9' => 'Set',
    'fin_mes_curto_10' => 'Out',
    'fin_mes_curto_11' => 'Nov',
    'fin_mes_curto_12' => 'Dez',

    // Política de Privacidade
    'lang_code' => 'pt-BR',
    'priv_titulo' => 'Política de Privacidade',
    'priv_atualizado' => 'Última atualização: 22 de junho de 2026',

    'priv_s1_titulo' => 'Introdução',
    'priv_s1_texto' => '%APP% ("nós", "nosso") é um serviço de agendamento pessoal que integra WhatsApp e Google Calendar. Esta política descreve como coletamos, usamos, armazenamos e protegemos seus dados pessoais, em conformidade com a Lei Geral de Proteção de Dados (LGPD — Lei 13.709/2018, Brasil) e a Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP, México).',

    'priv_s2_titulo' => 'Dados que coletamos',
    'priv_s2_texto' => 'Coletamos apenas os dados necessários para prestar o serviço:',
    'priv_s2_item1' => '<strong>Dados de cadastro:</strong> nome, e-mail, senha (armazenada com hash criptográfico) e número de telefone.',
    'priv_s2_item2' => '<strong>Dados de agenda:</strong> eventos criados, editados ou cancelados por você via WhatsApp, sincronizados com o Google Calendar.',
    'priv_s2_item3' => '<strong>Tokens de autenticação:</strong> tokens OAuth do Google, usados exclusivamente para acessar seu calendário com sua autorização.',
    'priv_s2_item4' => '<strong>Mensagens no WhatsApp:</strong> registramos o conteúdo das mensagens trocadas com o assistente para processamento e log de atendimento.',
    'priv_s2_item5' => '<strong>Dados de pagamento:</strong> processados diretamente pelo Stripe. Não armazenamos número de cartão, CVV ou dados bancários em nossos servidores.',

    'priv_s3_titulo' => 'Finalidade do tratamento',
    'priv_s3_texto' => 'Utilizamos seus dados para:',
    'priv_s3_item1' => 'Criar e gerenciar sua conta e assinatura.',
    'priv_s3_item2' => 'Processar comandos de agendamento recebidos via WhatsApp e sincronizar com o Google Calendar.',
    'priv_s3_item3' => 'Enviar lembretes e notificações sobre seus eventos.',
    'priv_s3_item4' => 'Melhorar o serviço e corrigir problemas técnicos.',

    'priv_s4_titulo' => 'Base legal (LGPD)',
    'priv_s4_texto' => 'O tratamento dos seus dados se baseia no consentimento (art. 7º, I) fornecido ao criar sua conta e autorizar o acesso ao Google Calendar, e na execução de contrato (art. 7º, V) para a prestação do serviço contratado. Para o envio de lembretes, a base é o legítimo interesse (art. 7º, IX), sendo que você pode desativar lembretes a qualquer momento nas configurações da sua conta.',

    'priv_s5_titulo' => 'Seus direitos',
    'priv_s5_texto' => 'Conforme a LGPD (Brasil) e a LFPDPPP (México), você tem direito a:',
    'priv_s5_item1' => '<strong>Acesso:</strong> solicitar uma cópia dos dados pessoais que mantemos sobre você.',
    'priv_s5_item2' => '<strong>Retificação:</strong> corrigir dados incompletos ou inexatos.',
    'priv_s5_item3' => '<strong>Cancelamento / Eliminação:</strong> solicitar a exclusão dos seus dados pessoais.',
    'priv_s5_item4' => '<strong>Oposição:</strong> opor-se ao tratamento dos seus dados para determinada finalidade.',
    'priv_s5_item5' => '<strong>Portabilidade:</strong> receber seus dados em formato estruturado e interoperável.',
    'priv_s5_item6' => '<strong>Revogação do consentimento:</strong> retirar o consentimento a qualquer momento, sem comprometer a licitude do tratamento já realizado.',

    'priv_s6_titulo' => 'Compartilhamento de dados',
    'priv_s6_texto' => 'Compartilhamos dados apenas com os serviços necessários à operação: Google (sincronização de calendário via OAuth), Stripe (processamento de pagamentos), Evolution API / WhatsApp (envio e recebimento de mensagens) e n8n (orquestração de automações). Não vendemos, alugamos ou cedemos seus dados a terceiros para fins de marketing.',

    'priv_s7_titulo' => 'Armazenamento e segurança',
    'priv_s7_texto' => 'Seus dados são armazenados em servidores com acesso restrito. Senhas são protegidas com hash criptográfico (bcrypt). Tokens do Google são armazenados de forma criptografada. Adotamos medidas técnicas e organizacionais para proteger seus dados contra acesso não autorizado, destruição, perda ou alteração.',

    'priv_s8_titulo' => 'Retenção de dados',
    'priv_s8_texto' => 'Mantemos seus dados enquanto sua conta estiver ativa. Ao solicitar a exclusão da conta, seus dados pessoais serão removidos em até 30 dias, exceto quando houver obrigação legal de retenção (como registros fiscais de pagamento).',

    'priv_s9_titulo' => 'Transferência internacional',
    'priv_s9_texto' => 'Seus dados podem ser processados em servidores localizados fora do Brasil ou do México (ex: Google Cloud, Stripe). Nesses casos, garantimos que os destinatários ofereçam nível adequado de proteção, conforme exigido pela LGPD (art. 33) e pela LFPDPPP (art. 36).',

    'priv_s10_titulo' => 'Contato e encarregado de dados',
    'priv_s10_texto' => 'Para exercer seus direitos ou esclarecer dúvidas sobre esta política, entre em contato pelo e-mail: contato@calendarioia.com. Nos termos da LGPD, o encarregado pelo tratamento de dados pessoais pode ser contatado no mesmo endereço. Para usuários no México, solicitações ARCO (Acceso, Rectificación, Cancelación y Oposición) podem ser enviadas ao mesmo e-mail e serão respondidas no prazo de 20 dias estabelecido pela LFPDPPP.',

    // Termos de Uso
    'termos_titulo' => 'Termos de Uso',
    'termos_atualizado' => 'Última atualização: 22 de junho de 2026',

    'termos_s1_titulo' => 'Aceitação dos termos',
    'termos_s1_texto' => 'Ao criar uma conta ou utilizar o %APP%, você concorda com estes Termos de Uso e com a nossa Política de Privacidade. Se não concordar, não utilize o serviço.',

    'termos_s2_titulo' => 'Descrição do serviço',
    'termos_s2_texto' => 'O %APP% é um serviço de agendamento pessoal que permite criar, listar, editar e cancelar eventos através de mensagens em linguagem natural no WhatsApp, com sincronização automática ao Google Calendar. O serviço inclui:',
    'termos_s2_item1' => 'Assistente de agendamento via WhatsApp com inteligência artificial.',
    'termos_s2_item2' => 'Sincronização bidirecional com o Google Calendar.',
    'termos_s2_item3' => 'Lembretes automáticos de eventos.',

    'termos_s3_titulo' => 'Cadastro e conta',
    'termos_s3_texto' => 'Para utilizar o serviço, você deve:',
    'termos_s3_item1' => 'Ter pelo menos 18 anos de idade ou a maioridade legal em sua jurisdição.',
    'termos_s3_item2' => 'Fornecer informações verdadeiras e atualizadas no cadastro.',
    'termos_s3_item3' => 'Manter a confidencialidade da sua senha. Você é responsável por todas as atividades realizadas com sua conta.',
    'termos_s3_item4' => 'Notificar-nos imediatamente em caso de uso não autorizado da sua conta.',

    'termos_s4_titulo' => 'Planos e pagamento',
    'termos_s4_texto' => 'O %APP% oferece planos pagos com ciclos mensal, trimestral ou anual, e pode oferecer um período de teste gratuito. Os preços são exibidos em pesos mexicanos (MXN) e cobrados via Stripe. A renovação é automática ao final de cada ciclo. Você pode cancelar a qualquer momento pelo painel do cliente; o acesso permanece ativo até o fim do ciclo já pago. Não realizamos reembolsos por períodos parciais, exceto quando exigido por lei aplicável.',

    'termos_s5_titulo' => 'Uso aceitável',
    'termos_s5_texto' => 'Você concorda em não utilizar o serviço para:',
    'termos_s5_item1' => 'Enviar mensagens automatizadas em massa (spam) via WhatsApp.',
    'termos_s5_item2' => 'Tentar acessar contas de outros usuários ou sistemas internos.',
    'termos_s5_item3' => 'Utilizar o serviço para qualquer finalidade ilegal ou que viole direitos de terceiros.',
    'termos_s5_item4' => 'Revender, sublicenciar ou redistribuir o acesso ao serviço sem autorização.',

    'termos_s6_titulo' => 'Propriedade intelectual',
    'termos_s6_texto' => 'Todo o conteúdo, marca, código e design do %APP% são de nossa propriedade ou licenciados para nós. Você mantém a propriedade dos dados e eventos que inserir no serviço. Ao utilizar o serviço, você nos concede uma licença limitada para processar seus dados exclusivamente para a prestação do serviço contratado.',

    'termos_s7_titulo' => 'Integrações com terceiros',
    'termos_s7_texto' => 'O serviço depende de plataformas de terceiros (Google, WhatsApp/Meta, Stripe). Não nos responsabilizamos por indisponibilidades, alterações de política ou interrupções nesses serviços. Em caso de descontinuação de uma integração essencial, notificaremos os usuários com antecedência razoável.',

    'termos_s8_titulo' => 'Limitação de responsabilidade',
    'termos_s8_texto' => 'O %APP% é fornecido "como está". Empenhamo-nos para manter o serviço estável e seguro, mas não garantimos disponibilidade ininterrupta. Não nos responsabilizamos por compromissos perdidos por falha de notificação, sincronização ou por indisponibilidade dos serviços de terceiros. Nossa responsabilidade total é limitada ao valor pago por você nos últimos 12 meses.',

    'termos_s9_titulo' => 'Suspensão e encerramento',
    'termos_s9_texto' => 'Reservamo-nos o direito de suspender ou encerrar sua conta em caso de violação destes termos, uso abusivo ou inadimplência. Você pode encerrar sua conta a qualquer momento pelo painel ou entrando em contato conosco. Ao encerrar, seus dados serão tratados conforme a Política de Privacidade.',

    'termos_s10_titulo' => 'Alterações nos termos',
    'termos_s10_texto' => 'Podemos atualizar estes termos periodicamente. Alterações relevantes serão comunicadas por e-mail ou notificação no serviço com pelo menos 15 dias de antecedência. O uso continuado do serviço após as alterações constitui aceitação dos novos termos.',

    'termos_s11_titulo' => 'Lei aplicável e foro',
    'termos_s11_texto' => 'Para usuários no Brasil, estes termos são regidos pela legislação brasileira, incluindo a LGPD, o Marco Civil da Internet (Lei 12.965/2014) e o Código de Defesa do Consumidor (Lei 8.078/1990), com foro na comarca do domicílio do consumidor. Para usuários no México, aplicam-se a LFPDPPP, a Ley Federal de Protección al Consumidor e demais leis aplicáveis, com jurisdição nos tribunais competentes da Cidade do México.',

    'termos_s12_titulo' => 'Contato',
    'termos_s12_texto' => 'Para dúvidas sobre estes termos, entre em contato pelo e-mail: contato@calendarioia.com.',
];
